import express from "express";
import { protect } from "../middleware/auth.middleware.js";
import { createPost, getPost, updatePost, deletePost, getFeed, getExplorePosts, toggleLike, toggleSave, addComment, deleteComment, getSavedPosts, getTaggedPosts, addReaction, sharePost, getPostAnalytics, uploadTempImage } from "../controllers/post.controller.js";
import { uploadPost, uploadTemp } from "../middleware/upload.middleware.js";
const router = express.Router();
router.use(protect);
router.get("/feed", getFeed);
router.get("/explore", getExplorePosts);
router.get("/saved", getSavedPosts);
router.get("/tagged/:userId", getTaggedPosts);
router.post("/", uploadPost, createPost);
router.post("/upload-temp", uploadTemp, uploadTempImage);
router.get("/:postId", getPost);
router.put("/:postId", updatePost);
router.delete("/:postId", deletePost);
router.post("/:postId/like", toggleLike);
router.post("/:postId/save", toggleSave);
router.post("/:postId/comments", addComment);
router.delete("/:postId/comments/:commentId", deleteComment);
router.post("/:postId/react", addReaction);
router.post("/:postId/share", sharePost);
router.get("/:postId/analytics", getPostAnalytics);
export default router;
